services:
  web:
    image: node:22
    working_dir: /app/marsa
    command: sh -c "npm install --no-audit --no-fund && npx ng serve --host 0.0.0.0 --port 4200 --allowed-hosts true --configuration development"
    volumes:
      - ./:/app
    ports:
      - "3000:4200"
    environment:
      - NG_CLI_ANALYTICS=false
      - CHOKIDAR_USEPOLLING=true
